### PR TITLE
remove dependency on django.utils.six (for Django 3.0)

### PR DESCRIPTION
**Pull request by terencehonles**

### CODE REVIEW

**Comment by terencehonles** [comment]
I added the CI fix from #391 which will close #367

**Comment by jdufresne** [comment]
Is this a duplicate of #387 (has been merged) or is there more here?

**Comment by terencehonles** [comment]
@jdufresne I didn't realize we'd drop Python 2 so soon. I think this is a duplicate, but I'm looking on mobile and I don't see something like https://github.com/niwinz/django-redis/commit/887204ec5915c4e52c2fe6476a5cfacd48110d6b in the diff for #387

**Comment by terencehonles** [comment]
Nevermind it looks like you merged #391

**Comment by dhcn** [comment]
When will this patch be released?

**Pull request closed without merging**
