### PR TITLE
Drop support for Python 2

### PR DESCRIPTION
**Pull request by jdufresne**
Python 2 support is nearing end of life. At the end of this year, it will no longer be supported, including for security issues.

Django has already dropped support for Python 2 in Django 2.0. Follow upstream to be more compatible with the master branch as tests now pass.

For more details, see https://pythonclock.org/

All code changes and clean ups that were noticed were done. Changes include:

- Remove `str`/`unicode` compatibility shims.
- Remove encoding cookies from source files. Python 3 interprets all files as utf-8 by default.
- Remove unnecessary `__future__` imports. The features are now built-in.
- Use modern and simpler `super()` syntax.
- Update the wheel configuration to reflect it is no longer universal.
- Update trove classifiers.
- And more …

Also remove supported for end of life Python 3.4. It went end of life 2019-03-18.

### CODE REVIEW

**Comment by jdufresne** [comment]
@niwinz Any thoughts on this? It would be great to get django-redis compatible with the upcoming Django 3.0 release.

**Comment by maxmalysh** [comment]
@niwinz could you please merge & release this?

**Comment by maxmalysh** [comment]
@jdufresne thanks for the PR! Adding Django 3.0 to the test matrix will be a a final touch for this PR.

**Comment by jdufresne** [comment]
Done in the latest commit! :slightly_smiling_face:

**Pull request merged**
