### PR TITLE
Enable universal wheel support

### PR DESCRIPTION
**Pull request by jdufresne**
See: http://pythonwheels.com/

Refs #231

### CODE REVIEW

**Comment by jdufresne** [comment]
Rebased to resolve merge conflicts.

**Comment by auvipy** [comment]
@niwinz I think its good for inclusion

**Comment by jdufresne** [comment]
@niwinz Thanks for the new release. Do you mind distributing the universal wheel as well? To do so, you can run the command:

```
$ python setup.py sdist bdist_wheel upload
```

More information here: http://pythonwheels.com/

Thanks!

**Comment by niwinz** [comment]
Hmm, I'm getting an error that bdist_wheel command does not exists executing that.

**Comment by niwinz** [comment]
Oh, yeah, I have missed that `wheel` package should be installed in order to upload my package :S

**Pull request merged**
