### PR TITLE
HerdClient exception handling improvements

### PR DESCRIPTION
**Pull request by brandoshmando**

### CODE REVIEW

**Comment by brandoshmando** [comment]
I know you just merged my other issue this morning but I noticed that exceptions were not being handled properly in the HerdClient for `get_many` and `set_many` calls. I made a few fixes there and improved the error messages being logged. Let me know any thoughts/changes you'd like me to make. Thanks!

Also, one of the tests keeps timing out on Travis CI which is what is causing the builds to fail.

**Comment by niwinz** [comment]
Thank you very much! At first quick review it seems ok for me. I try to get some time for it this weekend and release an other version with your fixes.

**Comment by niwinz** [comment]
This seems already merged but pr is not closed.

**Comment by brandoshmando** [comment]
@niwinz Is it merged into master? I'm not seeing the changes in the master branch. Just thought I'd double check with you. Thanks!

**Comment by niwinz** [comment]
Oh you are right! I completly confused with the changes done in the default client. Sorry.

**Comment by niwinz** [comment]
Now, the changes are squashed and merged  manually. Thanks!

**Pull request closed without merging**
